name: 'Post-Refresh: Load Data'

on:
  workflow_dispatch:
    inputs:
      sandbox:
        description: 'Environment'
        required: false
        type: environment

jobs:
  load-data:
    runs-on: ubuntu-22.04        
    steps:
      - uses: actions/checkout@v4    

      # - name: check sf folder
      #   run: ls -ltra ~/.local/share/

      # - name: list last modified folders in desc order
      #   run: sudo find / -type d -cmin -0.75 -exec stat --format='%y %n' {} + 2>/dev/null | sort -r
        
      # Cache SF CLI using the hash of installed plugins
      - name: Cache SF CLI & SFDMU
        uses: actions/cache@v4
        with:
          path: |
            ~/.local/share/sf/
            /usr/local/bin/sf
            /usr/local/lib/node_modules/@salesforce/
          key: sf-cli-SFDMU-${{ runner.os }}-v8

      - name: check for sfcli folder
        run: ls -ltra /usr/local/lib/node_modules

      - name: check bin for sf
        run: ls -ltra /usr/local/bin
        
      # Install SF CLI if not cached
      - name: Install SF CLI
        run: |
          if ! command -v sf &> /dev/null; then
            echo "SF CLI not found, installing..."
            npm install --global @salesforce/cli
          else
            echo "SF CLI already installed, skipping..."
          fi
          
      - name: check bin for sf
        run: ls -ltra /usr/local/bin/
        
      # - name: AFTER cli install list last modified folders in desc order
      #   run: |
      #     sudo find / \( -path "/proc" -o -path "/dev" -o -path "/sys" -o -path "~/.npm" \) -prune -o -maxdepth 6 -type d -cmin -0.75 -exec stat --format='%y %n' {} + 2>/dev/null | sort -r

      # - name: AFTER cli last modified pt 2
      #   run: |
      #     sudo find /lib /var /opt /home ~/.local/ -maxdepth 6 -type d -cmin -0.75 -exec stat --format='%y %n' {} + 2>/dev/null | sort -r
        
      # - name: check SF CLI installation
      #   run: |
      #     if ! command -v sf &> /dev/null; then
      #       echo "SF CLI not found"
      #     else
      #       echo "SF CLI already installed"
      #     fi

      # - name: check sf folder
      #   run: ls -ltra ~/.local/share/

      - name: Ensure package-lock exists
        run: touch package-lock.json
    
       # Cache SFDMU using the hash of installed plugins
      # - name: Cache SFDMU
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/.local/share/sf/    # Specify which directory to cache
      #     key: sfdmu-${{ runner.os }}-v2

      # Install SFDMU if not cached
      - name: Install SFDMU
        run: |
          if ! sf plugins --core | grep -q sfdmu; then
            echo "SFDMU not found, installing..."
            sf plugins install sfdmu --force
          else
            echo "SFDMU already installed, skipping..."
          fi

      # - name: AFTER SFDMU install list last modified folders in desc order
      #   run: |
      #     sudo find /usr /lib /var /opt /home ~/.local/ \( -path "/usr/local/lib/node_modules/@salesforce" \) -prune -o -maxdepth 5 -type d -cmin -0.75 -exec stat --format='%y %n' {} + 2>/dev/null | sort -r
        
      # - name: print local sf directory AFTER sfdmu
      #   run: ls -ltra ~/.local/share/sf/

      # Verify installations
      - name: Check Installed Plugins
        run: sf plugins --core

      - name: check which version of sf cli is installed
        run: sf --version

      - name: check which version of sf cli v2
        run: npm show @salesforce/cli version

      - name: which sf
        run: which sf
