name: 'Post-Refresh: Load Data'

on:
  workflow_dispatch:
    inputs:
      sandbox:
        description: 'Environment'
        required: false
        type: environment

jobs:
  load-data:
    runs-on: ubuntu-22.04        
    steps:
      - uses: actions/checkout@v4    

      - name: print local share directory before sf cli cache
        run: ls -ltra ~/.local/share/
        
      # Cache SF CLI using the hash of installed plugins
      - name: Cache SF CLI
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ~/.local/share/sf
          key: sf-cli-${{ runner.os }}-${{ hashFiles('/home/runner/.local/share/sf/package-lock.json') }}

      - name: print local share directory before sf cli
        run: ls -ltra ~/.local/share/
        
      # Install SF CLI if not cached
      - name: Install SF CLI
        run: |
          if ! command -v sf &> /dev/null; then
            echo "SF CLI not found, installing..."
            npm install --global @salesforce/cli
          else
            echo "SF CLI already installed, skipping..."
          fi

      - name: check SF CLI installation
        run: |
          if ! command -v sf &> /dev/null; then
            echo "SF CLI not found"
          else
            echo "SF CLI already installed"
          fi
      
#      - name: Print package-lock after SF CLI Install
#        run: cat package-lock.json

      - name: print plugins directory before sfdmu
        run: ls -ltra ~/.local/share/
        
      # Cache SFDMU using the hash of installed plugins
      - name: Cache SFDMU
        uses: actions/cache@v4
        with:
          path: ~/.local/share/sf/
          key: sfdmu-${{ runner.os }}-${{ hashFiles('/home/runner/.local/share/sf/package-lock.json') }}

      # Install SFDMU if not cached
      - name: Install SFDMU
        run: |
          if ! sf plugins --core | grep -q sfdmu; then
            echo "SFDMU not found, installing..."
            sf plugins install sfdmu --force
          else
            echo "SFDMU already installed, skipping..."
          fi

      - name: print local sf directory AFTER sfdmu
        run: ls -ltra ~/.local/share/sf/

      - name: cat plugins afer dmu
        run: cat "/home/runner/.local/share/sf/package-lock.json"

      - name: print package-lock AFTER sfdmu
        run: cat ~/.local/share/sf/package-lock.json
        
#      - name: Print package-lock after SFDMU Install
#        run: cat package-lock.json

      # Verify installations
      - name: Check Installed Plugins
        run: sf plugins --core
