name: 'Post-Refresh: Load Data'

on:
  workflow_dispatch:
    inputs:
      sandbox:
        description: 'Environment'
        required: false
        type: environment

jobs:
  load-data:
    runs-on: ubuntu-22.04        
    steps:
      - uses: actions/checkout@v4

      # Cache SF CLI installation
      - name: Cache SF CLI
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/.local/share/sf
          key: sf-cli-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: sf-cli-${{ runner.os }}-

      # Install SF CLI if not cached
      - name: Install SF CLI
        run: npm install --global @salesforce/cli
      
      - name: Print package-lock after SF CLI Install
        run: cat package-lock.json
        
      # Cache SFDMU plugin
      - name: Cache SFDMU
        uses: actions/cache@v2
        with:
          path: ~/.sf/plugins
          key: sfdmu-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: sfdmu-${{ runner.os }}-

      # Install SFDMU plugin if not cached
      - name: Install SFDMU
        run: sf plugins install sfdmu --force

      - name: Print package-lock after SFDMU Install
        run: cat package-lock.json

      # Verify installations
      - name: Check Installed Plugins
        run: sf plugins --core
